### ISSUE TITLE
How long for training the model

### ISSUE THREAD

**Issue by ShenZheng2000** [ML-GSAI/EGSDE#4]
Hello, authors! Thanks for your excellent work. I have several questons below.

(1) How long does it take to train your model on the dataset? It seems like your computational efficiency is not good compared with previous models (see Table 5). 

(2) Diffusion models are often pretrained on ImageNet (or other large-scale datasets) and finetuned on a smaller dataset due to their heavy computational complexity. Your model is not pretrained on ImageNet. Why can it still achieve such an excellent result on benchmark datasets? 

I am looking forward to your reply. Thanks!

**Comment by gracezhao1997** [comment]
Hi, sorry for the late reply.
(1) Table 5 is the inference time comparison rather than training time. Training the domain-specific feature extractor for 5K iterations takes 7 hours based on 5 2080Ti GPUs.  As for the diffusion model, we directly use the pretrained model on AFHQ dog provided by https://github.com/jychoi118/ilvr_adm  and retrain the diffusion model on CelebeA-HQ female using about 7 days using the code https://github.com/ermongroup/ddim. 
(2) On AFHQ dog dataset, we directly use the pretrained model on AFHQ dog provided by https://github.com/jychoi118/ilvr_adm. On CelebA-HQ female dataset, we retrain the diffusion model. We find actually training it for 20w iterations is enough. I guess the high quality human face dataset is easy to train.

**Comment by DavidXie03** [comment]
> Hi, sorry for the late reply. (1) Table 5 is the inference time comparison rather than training time. Training the domain-specific feature extractor for 5K iterations takes 7 hours based on 5 2080Ti GPUs. As for the diffusion model, we directly use the pretrained model on AFHQ dog provided by https://github.com/jychoi118/ilvr_adm and retrain the diffusion model on CelebeA-HQ female using about 7 days using the code https://github.com/ermongroup/ddim. (2) On AFHQ dog dataset, we directly use the pretrained model on AFHQ dog provided by https://github.com/jychoi118/ilvr_adm. On CelebA-HQ female dataset, we retrain the diffusion model. We find actually training it for 20w iterations is enough. I guess the high quality human face dataset is easy to train.

Thanks for detailed information. Could you please tell me the parameters you set during retraining the diffusion model(e.g. batch_size, lr)?

**Comment by gracezhao1997** [comment]
We use the default setting, e.g. lr=0.00002, batch_size=64 for 256*256 resolution
